//
//  ManageRouteMapModels.swift
//  Tripper
//
//  Created by Denis Cherniy on 07.04.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ManageRouteMap {
    
    struct AnnotationInfo {
        let id: String
        let latitude: Double
        let longitude: Double
    }
    
    // MARK: Use cases
    
    enum FetchAllAnnotationsInfo {
        struct Request {
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    enum SetAnnotation {
        struct Request {
            let latitude: Double
            let longitude: Double
        }
        struct Response {
            let id: String
            let latitude: Double
            let longitude: Double
        }
        struct ViewModel {
            let id: String
            let latitude: Double
            let longitude: Double
        }
    }
    
}
