//
//  CreateRoutePointPresenter.swift
//  Tripper
//
//  Created by Denis Cherniy on 07.04.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateRoutePointPresentationLogic {
    func presentRoutePointForm(response: CreateRoutePoint.FormRoutePoint.Response)
}

class CreateRoutePointPresenter: CreateRoutePointPresentationLogic {
    weak var viewController: CreateRoutePointDisplayLogic?
    
    private let dateFormatter: DateFormatter = {
        let dateFormatter = DateFormatter()
        dateFormatter.timeStyle = .none
        dateFormatter.dateStyle = .medium
        return dateFormatter
    }()
    
    // MARK: Do something
    
    func presentRoutePointForm(response: CreateRoutePoint.FormRoutePoint.Response) {
        let title = response.routePoint.title ?? ""
        let subtitle = response.routePoint.subtitle ?? ""
        
        let arrivalDate = response.routePoint.arrivalDate ?? Date()
        let arrivalDateString = dateFormatter.string(from: arrivalDate)
        
        let departureDate = response.routePoint.departureDate ?? Date()
        let departureDateString = dateFormatter.string(from: departureDate)
        
        let annotationForm = CreateRoutePoint.DisplayableAnnotationInfo(
            title: title, subtitle: subtitle, arrivalDate: arrivalDateString, departureDate: departureDateString)
        
        let viewModel = CreateRoutePoint.FormRoutePoint.ViewModel(annotationForm: annotationForm)
        viewController?.displayRoutePointForm(viewModel: viewModel)
    }
}
