//
//  CreateRoutePointViewControllerTests.swift
//  Tripper
//
//  Created by Denis Cherniy on 26.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TripManager
import XCTest

class CreateRoutePointViewControllerTests: XCTestCase {
    // MARK: Subject Under Test
    
    var sut: CreateRoutePointViewController!
    var routePointGateway: RoutePointGatewayMock!
    var window: UIWindow!
    
    // MARK: Test Lifecycle
    
    override func setUp() {
        routePointGateway = RoutePointGatewayMock(initialStorage: [])
        super.setUp()
        window = UIWindow()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test Setup
    
    func setupCreateRoutePointViewController(with routePoint: RoutePoint) {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = (storyboard.instantiateViewController(withIdentifier: "CreateRoutePointViewController") as! CreateRoutePointViewController)
        
        let interactor = CreateRoutePointInteractor()
        
        interactor.pointToSave = routePoint
        let presenter = CreateRoutePointPresenter()
        presenter.viewController = sut
        
        interactor.presenter = presenter
        let worker = CreateRoutePointWorker(routePointGateway: routePointGateway, orderNumberGenerator: OrderNumberGeneratorMock(), dateLimiter: DateLimiterMock())
        interactor.worker = worker
        
        sut.interactor = interactor
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Tests
    
    func testUIDataSetup() {
        let date = Date()
        let routePoint = RoutePoint(id: "11", orderNumber: 1, title: "San-Francisco", subtitle: "City in style of disco", latitude: 120, longitude: 133, arrivalDate: date, departureDate: date, isFinished: false)
        setupCreateRoutePointViewController(with: routePoint)
        
        loadView()
        sut.formRoutePoint()
        
        XCTAssertEqual(routePoint.title, sut.titleTextField.text!)
        XCTAssertEqual(routePoint.subtitle, sut.descriptionTextView.text)
    }
    
    func testRoutePointCreation() {
        let date = Date()
        let routePoint = RoutePoint(id: "11", orderNumber: 1, title: "San-Francisco", subtitle: "City in style of disco", latitude: 120, longitude: 133, arrivalDate: date, departureDate: date, isFinished: false)
        setupCreateRoutePointViewController(with: routePoint)
        
        loadView()
        sut.save(self)
        
        XCTAssertTrue(routePointGateway.insertedRoutePoint! == routePoint)
    }
}
