//
//  DetailRoutePointPresenter.swift
//  Tripper
//
//  Created by Denis Cherniy on 09.04.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailRoutePointPresentationLogic {
    func presentSomething(response: DetailRoutePoint.Something.Response)
}

class DetailRoutePointPresenter: DetailRoutePointPresentationLogic {
    weak var viewController: DetailRoutePointDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: DetailRoutePoint.Something.Response) {
        let viewModel = DetailRoutePoint.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
