//
//  DetailRoutePointInteractor.swift
//  Tripper
//
//  Created by Denis Cherniy on 09.04.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailRoutePointBusinessLogic {
    func doSomething(request: DetailRoutePoint.Something.Request)
}

protocol DetailRoutePointDataStore {
    var routePoint: RoutePoint? { get set }
}

class DetailRoutePointInteractor: DetailRoutePointBusinessLogic, DetailRoutePointDataStore {
    var presenter: DetailRoutePointPresentationLogic?
    var worker: DetailRoutePointWorker?
    var routePoint: RoutePoint?
    
    // MARK: Do something
    
    func doSomething(request: DetailRoutePoint.Something.Request) {
        worker = DetailRoutePointWorker()
        worker?.doSomeWork()
        
        let response = DetailRoutePoint.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
