//
//  DetailRoutePointWorker.swift
//  Tripper
//
//  Created by Denis Cherniy on 09.04.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Swinject

class DetailRoutePointWorker {
    let routePointGateway: RoutePointDataStore
    
    init(routePointGateway: RoutePointDataStore) {
        self.routePointGateway = routePointGateway
    }
    
    func delete(routePoint: RoutePoint) {
        routePointGateway.delete(routePoint)
    }
}
