//
//  FastNavigationInteractor.swift
//  Tripper
//
//  Created by Denis Cherniy on 19.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FastNavigationBusinessLogic {
    func fetchData(request: FastNavigation.FetchData.Request)
    func selectSubroute(request: FastNavigation.SelectSubroute.Request)
}

protocol FastNavigationDataStore {
}

class FastNavigationInteractor: FastNavigationBusinessLogic, FastNavigationDataStore {
    var presenter: FastNavigationPresentationLogic?
    var worker: FastNavigationWorker!
    
    // MARK: - Fetch Data
    var subroutes = [Subroute]()
    
    func fetchData(request: FastNavigation.FetchData.Request) {
        subroutes = worker.fetchSubroutes()
        
        presenter?.presentFetchedData(response: .init(subroutes: subroutes))
    }
    
    // MARK: Select Subroute
    
    func selectSubroute(request: FastNavigation.SelectSubroute.Request) {
        if request.index % 2 == 0 {
            presenter?.presentSelectedStaying(response: .init(subroute: subroutes[request.index]))
        } else {
            presenter?.presentSelectedInRoad(response: .init(subroute: subroutes[request.index]))
        }
    }
}
