//
//  FastNavigationViewControllerTests.swift
//  Tripper
//
//  Created by Denis Cherniy on 26.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Tripper
import XCTest

class FastNavigationViewControllerTests: XCTestCase {
    // MARK: Subject Under Test
    
    var sut: FastNavigationViewController!
    var window: UIWindow!
    var routePointGateway: RoutePointGatewayMock!
    var routeFragmentGateway: RouteFragmentGatewayMock!
    
    // MARK: Test Lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test Setup
    
    func setupGateways() {
        let date = Date()
        let routePoint = RoutePoint(id: "11", orderNumber: 1, title: "San-Francisco", subtitle: "City in style of disco", latitude: 120, longitude: 133, arrivalDate: date, departureDate: date)
        routePointGateway = RoutePointGatewayMock(initialStorage: [routePoint])
        routeFragmentGateway = RouteFragmentGatewayMock(initialStorage: [])
    }
    
    func setupFastNavigationViewController() {
        sut = FastNavigationViewController()
        
        let interactor = FastNavigationInteractor()
        
        let presenter = FastNavigationPresenter()
        presenter.viewController = sut
        
        interactor.presenter = presenter
        let worker = FastNavigationWorker(routePointGateway: routePointGateway, routeFragmentGateway: routeFragmentGateway)
        interactor.worker = worker
        
        let router = FastNavigationRouter()
        router.dataStore = interactor
        sut.router = router
        
        sut.interactor = interactor
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Tests
    
    func testUISetup() {
        setupGateways()
        setupFastNavigationViewController()
        
        loadView()
        sut.fetchData()
        
        XCTAssertTrue(sut.subroutes.count == 1)
    }
}
