//
//  FastNavigationViewController.swift
//  Tripper
//
//  Created by Denis Cherniy on 19.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FastNavigationDisplayLogic: class {
    func displaySomething(viewModel: FastNavigation.Something.ViewModel)
}

class FastNavigationViewController: UIViewController, FastNavigationDisplayLogic {
    var interactor: FastNavigationBusinessLogic?
    var router: (NSObjectProtocol & FastNavigationRoutingLogic & FastNavigationDataPassing)?
    
    // MARK: Object Lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = FastNavigationInteractor()
        let presenter = FastNavigationPresenter()
        let router = FastNavigationRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View Lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do Something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething() {
        let request = FastNavigation.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: FastNavigation.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
