//
//  FastNavigationInteractor.swift
//  Tripper
//
//  Created by Denis Cherniy on 19.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FastNavigationBusinessLogic {
    func doSomething(request: FastNavigation.Something.Request)
}

protocol FastNavigationDataStore {
    //var name: String { get set }
}

class FastNavigationInteractor: FastNavigationBusinessLogic, FastNavigationDataStore {
    var presenter: FastNavigationPresentationLogic?
    var worker: FastNavigationWorker?
    //var name: String = ""
    
    // MARK: Do Something
    
    func doSomething(request: FastNavigation.Something.Request) {
        worker = FastNavigationWorker()
        worker?.doSomeWork()
        
        let response = FastNavigation.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
