//
//  FastNavigationPresenter.swift
//  Tripper
//
//  Created by Denis Cherniy on 19.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FastNavigationPresentationLogic {
    func presentSomething(response: FastNavigation.Something.Response)
}

class FastNavigationPresenter: FastNavigationPresentationLogic {
    weak var viewController: FastNavigationDisplayLogic?
    
    // MARK: Do Something
    
    func presentSomething(response: FastNavigation.Something.Response) {
        let viewModel = FastNavigation.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
