//
//  FastNavigationRouter.swift
//  Tripper
//
//  Created by Denis Cherniy on 19.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FastNavigationRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol FastNavigationDataPassing {
    var dataStore: FastNavigationDataStore? { get }
}

class FastNavigationRouter: NSObject, FastNavigationRoutingLogic, FastNavigationDataPassing {
    weak var viewController: FastNavigationViewController?
    var dataStore: FastNavigationDataStore?
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?) {
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: FastNavigationViewController, destination: SomewhereViewController) {
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing Data
    
    //func passDataToSomewhere(source: FastNavigationDataStore, destination: inout SomewhereDataStore) {
    //  destination.name = source.name
    //}
}
