//
//  FastNavigationPresenter.swift
//  Tripper
//
//  Created by Denis Cherniy on 19.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation

protocol FastNavigationPresentationLogic {
    func presentFetchedData(response: FastNavigation.FetchData.Response)
    func presentSelectedStaying(response: FastNavigation.SelectSubroute.Response)
    func presentSelectedInRoad(response: FastNavigation.SelectSubroute.Response)
}

class FastNavigationPresenter: FastNavigationPresentationLogic {
    weak var viewController: FastNavigationDisplayLogic?
    
    // MARK: - Fetch Data
    
    func presentFetchedData(response: FastNavigation.FetchData.Response) {
        viewController?.displayFetchedData(viewModel: .init(subroutes: response.subroutes))
    }
    
    // MARK: Select Subroute
    
    func presentSelectedStaying(response: FastNavigation.SelectSubroute.Response) {
        let coordinate = (response.subroute as! FastNavigation.Staying).coordinate
        
        viewController?.displaySelectedSubroute(viewModel: .init(coordinates: [coordinate]))
    }
    
    func presentSelectedInRoad(response: FastNavigation.SelectSubroute.Response) {
        let coordinates = (response.subroute as! FastNavigation.InRoad).coordinates
        
        viewController?.displaySelectedSubroute(viewModel: .init(coordinates: coordinates))
    }
}
