//
//  FastNavigationPresenter.swift
//  Tripper
//
//  Created by Denis Cherniy on 19.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FastNavigationPresentationLogic {
    func presentFetchedData(response: FastNavigation.FetchData.Response)
}

class FastNavigationPresenter: FastNavigationPresentationLogic {
    weak var viewController: FastNavigationDisplayLogic?
    
    // MARK: - Fetch Data
    
    func presentFetchedData(response: FastNavigation.FetchData.Response) {
        var subroutes = [Subroute]()
        
        let fetchedRoutePoints = response.routePoints
        for index in 0..<(fetchedRoutePoints.count) {
            let routePoint = fetchedRoutePoints[index]
            let timeToStayInSeconds = Int(routePoint.departureDate.timeIntervalSince(routePoint.arrivalDate))
            let staying = ListRoute.Staying(title: routePoint.title, timeInSeconds: timeToStayInSeconds, description: routePoint.subtitle)
            subroutes.append(staying)
            
            if index < fetchedRoutePoints.count - 1 {
                let inRoad = ListRoute.InRoad(seconds: routePoint.timeToNextPointInSeconds ?? 0,
                                              metres: routePoint.distanceToNextPointInMeters ?? 0)
                subroutes.append(inRoad)
            }
        }
        
        viewController?.displayFetchedData(viewModel: .init(subroutes: subroutes))
    }
}
