//
//  SearchPresenter.swift
//  Tripper
//
//  Created by Denis Cherniy on 16.06.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentSomething(response: Search.Something.Response)
}

class SearchPresenter: SearchPresentationLogic {
    weak var viewController: SearchDisplayLogic?
    
    // MARK: Do Something
    
    func presentSomething(response: Search.Something.Response) {
        let viewModel = Search.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
