//
//  SearchModels.swift
//  Tripper
//
//  Created by Denis Cherniy on 16.06.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation

enum Search {
    // MARK: Use Cases
    
    enum PerformSearch {
        struct Request {
            let query: String
        }
        struct Response {
            let pointsInfo: [PointInfo]
        }
        struct ViewModel {
            let points: [String]
        }
    }
    
    enum SelectEntry {
        struct Request {
            let entryNumber: Int
        }
        struct Response {
            let latitude: Double
            let longitude: Double
        }
        struct ViewModel {
            let coordinate: CLLocationCoordinate2D
        }
    }

}
