//
//  SearchInteractor.swift
//  Tripper
//
//  Created by Denis Cherniy on 16.06.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic {
    func performSearch(request: Search.PerformSearch.Request)
}

protocol SearchDataStore {
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore {
    var presenter: SearchPresentationLogic?
    var worker: SearchWorker?
    
    // MARK: - Perform Search
    
    func performSearch(request: Search.PerformSearch.Request) {
        worker!.search(with: request.query, completionHandler: { pointsInfo in
            self.presenter?.presentPerformedSearch(response: .init(pointsInfo: pointsInfo))
        })
    }
}
