//
//  CreateRoutePointWorkerTests.swift
//  Tripper
//
//  Created by Denis Cherniy on 26.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Tripper
import XCTest

class CreateRoutePointWorkerTests: XCTestCase {
    // MARK: Subject Under Test
    
    var sut: CreateRoutePointWorker!
    
    // MARK: Test Lifecycle
    
    override func setUp() {
        super.setUp()
        setupCreateRoutePointWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test Setup
    
    func setupCreateRoutePointWorker() {
        
    }
}
