//
//  ListRoutePresenter.swift
//  Tripper
//
//  Created by Denis Cherniy on 16.04.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListRoutePresentationLogic {
    func presentSomething(response: ListRoute.Something.Response)
}

class ListRoutePresenter: ListRoutePresentationLogic {
    weak var viewController: ListRouteDisplayLogic?
    
    // MARK: Do Something
    
    func presentSomething(response: ListRoute.Something.Response) {
        let viewModel = ListRoute.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
