//
//  ListRouteInteractor.swift
//  Tripper
//
//  Created by Denis Cherniy on 16.04.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListRouteBusinessLogic {
    func doSomething(request: ListRoute.Something.Request)
}

protocol ListRouteDataStore {
    //var name: String { get set }
}

class ListRouteInteractor: ListRouteBusinessLogic, ListRouteDataStore {
    var presenter: ListRoutePresentationLogic?
    var worker: ListRouteWorker?
    //var name: String = ""
    
    // MARK: Do Something
    
    func doSomething(request: ListRoute.Something.Request) {
        worker = ListRouteWorker()
        worker?.doSomeWork()
        
        let response = ListRoute.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
