//
//  ListRouteInteractor.swift
//  Tripper
//
//  Created by Denis Cherniy on 16.04.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListRouteBusinessLogic {
    func fetchData(request: ListRoute.FetchData.Request)
}

protocol ListRouteDataStore {
}

class ListRouteInteractor: ListRouteBusinessLogic, ListRouteDataStore {
    var presenter: ListRoutePresentationLogic?
    var worker: ListRouteWorker?
    
    // MARK: Do Something
    
    func fetchData(request: ListRoute.FetchData.Request) {
        let subroutes = worker!.fetchSubroutes()
        let response = ListRoute.FetchData.Response(subroutes: subroutes)
        presenter?.presentFetchData(response: response)
    }
}
