//
//  ListRouteModels.swift
//  Tripper
//
//  Created by Denis Cherniy on 16.04.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Subroute {
    var title: String { get }
    var timeInSeconds: Int { get }
}

enum ListRoute {
    
    struct Staying: Subroute {
        var title: String
        var timeInSeconds: Int
        var description: String
    }
    
    struct InRoad: Subroute {
        var title: String
        var timeInSeconds: Int
        var metres: Int
        
        init(title: String = "In Road", seconds: Int, metres: Int) {
            self.title = title
            timeInSeconds = seconds
            self.metres = metres
        }
    }
    
    // MARK: Use Cases
    
    enum FetchData {
        struct Request {
        }
        struct Response {
            let subroutes: [Subroute]
        }
        struct ViewModel {
            let subroutes: [Subroute]
        }
    }
}
