//
//  DetailRoutePointViewControllerTests.swift
//  Tripper
//
//  Created by Denis Cherniy on 26.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Tripper
import XCTest

class DetailRoutePointViewControllerTests: XCTestCase {
    // MARK: Subject Under Test
    
    var sut: DetailRoutePointViewController!
    var window: UIWindow!
    var routePointGateway: RoutePointGatewayMock!
    
    // MARK: Test Lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        routePointGateway = RoutePointGatewayMock(initialStorage: [])
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test Setup
    
    func setupDetailRoutePointViewController(with routePoint: RoutePoint) {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = (storyboard.instantiateViewController(withIdentifier: "DetailRoutePointViewController") as! DetailRoutePointViewController)
        
        let interactor = DetailRoutePointInteractor()
        
        interactor.routePoint = routePoint
        let presenter = DetailRoutePointPresenter()
        presenter.viewController = sut
        
        interactor.presenter = presenter
        let worker = DetailRoutePointWorker(routePointGateway: routePointGateway)
        interactor.worker = worker
        
        let router = DetailRoutePointRouterMock()
        router.dataStore = interactor
        sut.router = router
        
        sut.interactor = interactor
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Tests
    
    func testUISetup() {
        let date = Date()
        let routePoint = RoutePoint(id: "11", orderNumber: 1, title: "San-Francisco", subtitle: "City in style of disco", latitude: 120, longitude: 133, arrivalDate: date, departureDate: date, timeToNextPointInSeconds: 120, distanceToNextPointInMeters: 120)
        setupDetailRoutePointViewController(with: routePoint)
        
        loadView()
        
        XCTAssertTrue(sut.titleLabel.text! == routePoint.title)
        XCTAssertTrue(sut.descriptionTextView.text == routePoint.subtitle)
    }
    
    func testDeleteRoutePoint() {
        let date = Date()
        let routePoint = RoutePoint(id: "11", orderNumber: 1, title: "San-Francisco", subtitle: "City in style of disco", latitude: 120, longitude: 133, arrivalDate: date, departureDate: date, timeToNextPointInSeconds: 120, distanceToNextPointInMeters: 120)
        setupDetailRoutePointViewController(with: routePoint)
        
        loadView()
        (sut.interactor as? DetailRoutePointInteractor)?.worker = DetailRoutePointWorker(routePointGateway: routePointGateway)
        sut.deleteRoutePoint()
        
        XCTAssertTrue(routePointGateway.deletedRoutePoint! == routePoint)
    }
}
