//
//  DetailRoutePointPresenterTests.swift
//  Tripper
//
//  Created by Denis Cherniy on 26.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Tripper
import XCTest

class DetailRoutePointPresenterTests: XCTestCase {
    // MARK: Subject Under test
    
    var sut: DetailRoutePointPresenter!
    
    // MARK: Test Lifecycle
    
    override func setUp() {
        super.setUp()
        setupDetailRoutePointPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test Setup
    
    func setupDetailRoutePointPresenter() {
        sut = DetailRoutePointPresenter()
    }
}
