//
//  ManageRouteMapInteractorTests.swift
//  Tripper
//
//  Created by Denis Cherniy on 14.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Tripper
import XCTest

class ManageRouteMapInteractorTests: XCTestCase {
    // MARK: Subject Under Test
    
    var sut: ManageRouteMapInteractor!
    
    // MARK: Test Lifecycle
    
    override func setUp() {
        super.setUp()
        setupManageRouteMapInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test Setup
    
    func setupManageRouteMapInteractor() {
        sut = ManageRouteMapInteractor()
    }
    
    // MARK: Tests
    
    func testDoSomething() {
        // Given
        let spy = ManageRouteMapPresentationLogicSpy()
        sut.presenter = spy
//        let request = ManageRouteMap.Something.Request()
        
        // When
//        sut.doSomething(request: request)
        
        // Then
//        XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    }
}
