//
//  ManageRouteMapViewControllerTests.swift
//  Tripper
//
//  Created by Denis Cherniy on 14.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Tripper
import XCTest

class ManageRouteMapViewControllerTests: XCTestCase {
    // MARK: Subject Under Test
    
    var sut: ManageRouteMapViewController!
    var window: UIWindow!
    
    // MARK: Test Lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupManageRouteMapViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test Setup
    
    func setupManageRouteMapViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "ManageRouteMapViewController") as! ManageRouteMapViewController
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Tests
    
    func testShouldDoSomethingWhenViewIsLoaded() {
        // Given
        let spy = ManageRouteMapBusinessLogicSpy()
        sut.interactor = spy
        
        // When
        loadView()
        
        // Then
//        XCTAssertTrue(spy.doSomethingCalled, "viewDidLoad() should ask the interactor to do something")
    }
    
    func testDisplaySomething() {
        // Given
//        let viewModel = ManageRouteMap.Something.ViewModel()
        
        // When
        loadView()
//        sut.displaySomething(viewModel: viewModel)
        
        // Then
        //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
    }
}
