//
//  ManageRouteMapPresenterTests.swift
//  Tripper
//
//  Created by Denis Cherniy on 14.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Tripper
import XCTest

class ManageRouteMapPresenterTests: XCTestCase {
    // MARK: Subject Under test
    
    var sut: ManageRouteMapPresenter!
    
    // MARK: Test Lifecycle
    
    override func setUp() {
        super.setUp()
        setupManageRouteMapPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test Setup
    
    func setupManageRouteMapPresenter() {
        sut = ManageRouteMapPresenter()
    }
    
    // MARK: Tests
    
    func testPresentSomething() {
        // Given
        let spy = ManageRouteMapDisplayLogicSpy()
        sut.viewController = spy
//        let response = ManageRouteMap.Something.Response()
        
        // When
//        sut.presentSomething(response: response)
        
        // Then
//        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
