//
//  ManageRouteMapWorkerTests.swift
//  Tripper
//
//  Created by Denis Cherniy on 14.05.2020.
//  Copyright (c) 2020 Denis Cherniy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Tripper
import XCTest

class ManageRouteMapWorkerTests: XCTestCase {
    // MARK: Subject Under Test
    
    var sut: ManageRouteMapWorker!
    
    // MARK: Test Lifecycle
    
    override func setUp() {
        super.setUp()
        setupManageRouteMapWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test Setup
    
    func setupManageRouteMapWorker() {
//        sut = ManageRouteMapWorker()
    }
    
    // MARK: Test Doubles
    
    // MARK: Tests
    
    func testSomething() {
        // Given
        
        // When
        
        // Then
    }
}
